
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    develop:
      watch: 
        - path: ./main.py
          target: .
          action: sync 
        - path : ./requirements.txt
          action : rebuild
        - path: .
          target: .
          action: sync
volumes: 
 bootcamp:
  